# formation creates network resources (vpc, subnet, ig, igconnection, route, routetable, routableassociation)
---
Resources:
  ASTempVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
  
  ASTempSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/16
      VpcId: !Ref ASTempVPC
      MapPublicIpOnLaunch: True

  ASTempRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: 
      - ASTempVPC
    Properties:
      VpcId: !Ref ASTempVPC

  ASTempRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
      - ASTempSubnet
    Properties: 
      RouteTableId: !Ref ASTempRouteTable
      SubnetId: !Ref ASTempSubnet

  ASTempInternetGateway:
    Type: AWS::EC2::InternetGateway

  ASTempInternetGatewayConnnection:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref ASTempInternetGateway
      VpcId: !Ref ASTempVPC
    
  ASTempRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId: !Ref ASTempRouteTable
      GatewayId: !Ref ASTempInternetGateway


# exported for use in other formations
Outputs:
  ASTempVPCOutput:
    Description:  EC2 output value.
    Value: !Ref ASTempVPC
    Export:
      Name: ASTempVPC1ID

  ASTempSubnetOutput:
    Description:  EC2 output value.
    Value: !Ref ASTempSubnet
    Export:
      Name: ASTempSubnet1ID